CREATE TABLE IF NOT EXISTS study_program (
  id INTEGER PRIMARY KEY NOT NULL,
  major_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (major_id) REFERENCES major(id)
);
