CREATE TABLE IF NOT EXISTS file (
  id INTEGER PRIMARY KEY NOT NULL,
  mahasiswa_id INTEGER,
  dosen_id INTEGER,
  upload_name TEXT NOT NULL,
  random_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
