CREATE TABLE IF NOT EXISTS news (
  id INTEGER PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  thumbnail_file_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (thumbnail_file_id) REFERENCES file(id)
);
