CREATE TABLE IF NOT EXISTS class (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  enroll_key TEXT NOT NULL UNIQUE,
  schedule INTEGER NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
