CREATE TABLE IF NOT EXISTS major (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS study_program (
  id INTEGER PRIMARY KEY NOT NULL,
  major_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (major_id) REFERENCES major(id)
);

CREATE TABLE IF NOT EXISTS file (
  id INTEGER PRIMARY KEY NOT NULL,
  mahasiswa_id INTEGER,
  dosen_id INTEGER,
  upload_name TEXT NOT NULL,
  random_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mahasiswa (
  id INTEGER PRIMARY KEY NOT NULL,
  major_id INTEGER NOT NULL,
  study_program_id INTEGER NOT NULL,
  nim TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (major_id) REFERENCES major(id),
  FOREIGN KEY (study_program_id) REFERENCES study_program(id)
);

CREATE TABLE IF NOT EXISTS dosen (
  id INTEGER PRIMARY KEY NOT NULL,
  nip TEXT NOT NULL,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news (
  id INTEGER PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  thumbnail_file_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (thumbnail_file_id) REFERENCES file(id)
);

CREATE TABLE IF NOT EXISTS class (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  enroll_key TEXT NOT NULL UNIQUE,
  schedule INTEGER NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class_enrollment (
  id INTEGER PRIMARY KEY NOT NULL,
  class_id INTEGER NOT NULL,
  mahasiswa_id INTEGER,
  dosen_id INTEGER,
  admin_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (class_id) REFERENCES class(id),
  FOREIGN KEY (mahasiswa_id) REFERENCES mahasiswa(id),
  FOREIGN KEY (dosen_id) REFERENCES dosen(id),
  FOREIGN KEY (admin_id) REFERENCES admin(id)
);

CREATE TABLE IF NOT EXISTS post (
  id INTEGER PRIMARY KEY NOT NULL,
  class_id INTEGER NOT NULL,
  class_enrollment_id INTEGER NOT NULL,
  file_id INTEGER,
  message TEXT,
  type TEXT NOT NULL DEFAULT 'post',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (class_id) REFERENCES class(id),
  FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollment(id),
  FOREIGN KEY (file_id) REFERENCES file(id)
);

CREATE TABLE IF NOT EXISTS task (
  id INTEGER PRIMARY KEY NOT NULL,
  post_id INTEGER NOT NULL,
  class_enrollment_id INTEGER NOT NULL,
  file_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES post(id),
  FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollment(id),
  FOREIGN KEY (file_id) REFERENCES file(id)
);

CREATE TABLE IF NOT EXISTS presence (
  id INTEGER PRIMARY KEY NOT NULL,
  class_enrollment_id INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'hadir',
  late_time INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollment(id)
);
CREATE TABLE IF NOT EXISTS major (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS study_program (
  id INTEGER PRIMARY KEY NOT NULL,
  major_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (major_id) REFERENCES major(id)
);

CREATE TABLE IF NOT EXISTS file (
  id INTEGER PRIMARY KEY NOT NULL,
  mahasiswa_id INTEGER,
  dosen_id INTEGER,
  upload_name TEXT NOT NULL,
  random_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mahasiswa (
  id INTEGER PRIMARY KEY NOT NULL,
  major_id INTEGER NOT NULL,
  study_program_id INTEGER NOT NULL,
  nim TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (major_id) REFERENCES major(id),
  FOREIGN KEY (study_program_id) REFERENCES study_program(id)
);

CREATE TABLE IF NOT EXISTS dosen (
  id INTEGER PRIMARY KEY NOT NULL,
  nip TEXT NOT NULL,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news (
  id INTEGER PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  thumbnail_file_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (thumbnail_file_id) REFERENCES file(id)
);

CREATE TABLE IF NOT EXISTS class (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  enroll_key TEXT NOT NULL UNIQUE,
  schedule INTEGER NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class_enrollment (
  id INTEGER PRIMARY KEY NOT NULL,
  class_id INTEGER NOT NULL,
  mahasiswa_id INTEGER,
  dosen_id INTEGER,
  admin_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (class_id) REFERENCES class(id),
  FOREIGN KEY (mahasiswa_id) REFERENCES mahasiswa(id),
  FOREIGN KEY (dosen_id) REFERENCES dosen(id),
  FOREIGN KEY (admin_id) REFERENCES admin(id)
);

CREATE TABLE IF NOT EXISTS post (
  id INTEGER PRIMARY KEY NOT NULL,
  class_id INTEGER NOT NULL,
  class_enrollment_id INTEGER NOT NULL,
  file_id INTEGER,
  message TEXT,
  type TEXT NOT NULL DEFAULT 'post',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (class_id) REFERENCES class(id),
  FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollment(id),
  FOREIGN KEY (file_id) REFERENCES file(id)
);

CREATE TABLE IF NOT EXISTS task (
  id INTEGER PRIMARY KEY NOT NULL,
  post_id INTEGER NOT NULL,
  class_enrollment_id INTEGER NOT NULL,
  file_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES post(id),
  FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollment(id),
  FOREIGN KEY (file_id) REFERENCES file(id)
);

CREATE TABLE IF NOT EXISTS presence (
  id INTEGER PRIMARY KEY NOT NULL,
  class_enrollment_id INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'hadir',
  late_time INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollment(id)
);
